# Generated by Django 4.2.3 on 2023-07-03 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employees',
            name='id_number',
            field=models.CharField(max_length=12, verbose_name='ИИН'),
        ),
    ]
